
#include "bagl_font_lucida_console_8.inc"

#include "bagl_font_open_sans_bold_13px.inc"
#include "bagl_font_open_sans_bold_21px.inc"
#include "bagl_font_open_sans_light_13px.inc"
#include "bagl_font_open_sans_light_14px.inc"
#include "bagl_font_open_sans_light_21px.inc"
#include "bagl_font_open_sans_semibold_18px.inc"

#include "bagl_font_comic_sans_ms_20px.inc"
#include "bagl_font_open_sans_extrabold_11px.inc"

#include "bagl_font_open_sans_light_16px.inc"

#include "bagl_font_open_sans_regular_11px.inc"

